Repository recycle-me-org/recycle-me-ui, pull requests merged in 2021-12, with the labels that each got.

#10 Setup
  README.md
  cypress.json
  cypress/fixtures/example.json
  cypress/plugins/index.js
  cypress/support/commands.js
  cypress/support/index.js
  package-lock.json
  package.json
  src/App.css
  src/App.js
  src/App.test.js
  src/components/App/App.css
  src/components/App/App.js
  src/components/ExchangeRates/ExchangeRates.js
  src/components/Footer/Footer.css
  src/components/Footer/Footer.js
  src/components/Map/Map.css
  src/components/Map/Map.js
  src/components/NavBar/NavBar.css
  src/components/NavBar/NavBar.js
  src/components/SearchBar/SearchBar.css
  src/components/SearchBar/SearchBar.js
  src/index.css
  src/index.js
  src/logo.svg
  src/reportWebVitals.js
  src/setupTests.js
  yarn.lock
Labels: chore

#11 Components
  public/index.html
  src/components/App/App.css
  src/components/App/App.js
  src/components/Footer/Footer.css
  src/components/Footer/Footer.js
  src/components/LandingPage/LandingPage.css
  src/components/LandingPage/LandingPage.js
  src/components/NavBar/NavBar.css
  src/components/NavBar/NavBar.js
  src/images/landing-page-background.jpg
  src/images/recycle.png
  src/images/reduce-reuse-recycle.png
Labels: chore

#14 Feature/search bar
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  src/components/App/App.css
  src/components/App/App.js
  src/components/NavBar/NavBar.css
  src/components/NavBar/NavBar.js
  src/components/SearchBar/SearchBar.css
  src/components/SearchBar/SearchBar.js
  src/index.css
Labels: enhancement

#31 Feature/google map setup
  package-lock.json
  package.json
  src/components/Map/Map.js
Labels: enhancement

#32 Feature/top secret key
  .gitignore
  package-lock.json
  package.json
  src/components/Map/Map.js
Labels: chore

#33 Feature/recycle instructions image
  .env
  src/components/App/App.js
  src/components/LandingPage/LandingPage.js
  src/components/Map/Map.js
  src/components/RecycleInstructionsImage/RecycleInstructionsImage.css
  src/components/RecycleInstructionsImage/RecycleInstructionsImage.js
  src/images/recycle-instructions.png
  src/images/tutorial.png
Labels: chore

#35 Feature/clickable map markers
  .env
  public/index.html
  src/assets/landing-page-background.jpg
  src/assets/recycle-instructions.png
  src/assets/recycle.png
  src/components/App/App.js
  src/components/ExchangeRates/ExchangeRates.js
  src/components/Footer/Footer.js
  src/components/LandingPage/LandingPage.css
  src/components/LandingPage/LandingPage.js
  src/components/Map/Map.css
  src/components/Map/Map.js
  src/components/NavBar/NavBar.js
  src/components/RecycleInstructionsImage/RecycleInstructionsImage.css
  src/components/RecycleInstructionsImage/RecycleInstructionsImage.js
  src/components/SearchBar/SearchBar.css
  src/images/reduce-reuse-recycle.png
  src/images/tutorial.png
  src/images/working-hands.jpg
  src/index.js
  src/placeDetails.js
Labels: chore

#36 Component/recycle tips
  package-lock.json
  package.json
  src/assets/recycle-instructions.png
  src/components/App/App.js
  src/components/LandingPage/LandingPage.css
  src/components/LandingPage/LandingPage.js
  src/components/Map/Map.js
  src/components/MaterialsDropdown/MaterialsDropdown.js
  src/components/NavBar/NavBar.css
  src/components/NavBar/NavBar.js
  src/components/RecyclingTips/RecyclingTips.css
  src/components/RecyclingTips/RecyclingTips.js
  src/components/SearchBar/SearchBar.css
  src/components/SearchBar/SearchBar.js
  src/index.css
  src/index.js
Labels: chore

#39 Place id query new
  cypress/integration/SearchBar.js
  src/components/App/App.js
  src/components/Map/Map.css
  src/components/Map/Map.js
  src/components/NavBar/NavBar.js
  src/components/NoMatch/NoMatch.js
  src/components/SearchBar/SearchBar.js
  src/placeDetails.js
Labels: bug

#43 Update tagline overlay
  src/components/LandingPage/LandingPage.css
  src/components/LandingPage/LandingPage.js
  src/components/NavBar/NavBar.css
Labels: chore
